### PR TITLE
Allow .bandit config-file

### LINKED ISSUE #12: Allow .bandit name for the config file
Hi,

would it be possible to use also `.bandit` name for the config file, since it is the default?

Or at least write somewhere a note to be able to get the right name easily, so people do not need to go through the code:
https://github.com/codacy/codacy-bandit/blob/master/src/main/scala/codacy/bandit/Bandit.scala#L68

Thanks in advance!

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
- Allow .bandit config file.
- Mention config-file names in the description and correct link to the bandit repo.

Resolves #12 

------

What about the change in docs here: https://support.codacy.com/hc/en-us/articles/207994335-Code-Patterns#5-existing-tools

### CODE REVIEW

**Comment by rtfpessoa** [comment]
This can take a day to reach prod. I will post here when it is live.

**Comment by lachmanfrantisek** [comment]
@rtfpessoa  Thanks!

**Comment by rtfpessoa** [comment]
This is released

**Comment by lachmanfrantisek** [comment]
@rtfpessoa Thanks for the info.

**Pull request merged**
